language: crystal

notifications:
  email: false
  flowdock:
    secure: AI9j6Q9HHF+/mr/7Vh7/HgZgJKJZKqilBXqDPd7qVXZpq3hcTpLaFqx7u5WQRx1Zz/pmxr2wkMPx5SGkFwiYPKVamsUeg20y3ekwmYktZSV1hfNwpJ0fBqGvmN5wM4rIO2bekJSkqGMNaOUWjTG3ZOk/b1dHj1GOhFVCycZx7erdeRDUfomcjRPI8m7DvoQ4oNoX+XyPaS6hICUY9jdpUauhA6t4iv+kdv/ZrmNfatFcJboR+ytZ43OwiNo9pME5RIwy3LTxUrqnmqcQqPxO0Abhogs64o51iIGXeIZWDq1+Cd1764aPCjamFFP/kaTGlpu02kwYGX/Qde8piXDQ7tG02BXBgHAO0ZLy1WY2xFGhEruRbyqAJZCuwlcnNPQNpG+KonJwiH5hhyDgQxvHGSVl01m3pmgdLTyFkt3DMU+w/lYuX4z6276SdCuqZs430gX/uw5DfKnJ0dA2mxTtvK33EroXom6+CZcMiHEnaike1mWutbwoX2N4DmEcnL7MUQ0hfj6ocdDqU+E5xPme3tlGz47QFRcf854nVLYT76n/cdwHrkRxvU24aTJlFyZ15LsqWoOGhqSt71HQXbQ6XWaIM7dyqNFexR3XMzEq3fpbdOB3UrGzpAOlM/YItqfrYpBUI7jDfDApe/HVCi1ZUi1jrBb3/JqrTMSgprKP5cs=
